### PR TITLE
fix: add click handle function to Filter button

### PR DESCRIPTION
**Pull request by mirestrepo**
This is a small PR to connect the Filter button to it's handler

### CODE REVIEW

**Comment by mirestrepo** [comment]
Fixes #140

**Review by tdivoll — APPROVED** [review]
The code looks good to me. The parentheses get me every time with JS/TS. I think I would need to log in to the researcher site to see the button on the frontend? I also see a reCAPTCHA warning hiding on the bottom right of the home page: "ERROR for site owner:
Invalid domain for site key"

**Review by eldu — APPROVED** [review]
Looks good to me! I see the same error that Tim does, perhaps we should add in an issue for it? Does it happen on the live site as well?

**Comment by mirestrepo** [comment]
@eldu @tdivoll Yes the captcha only works with the registered url with is not the preview one. I can make an issue to look into having a pattern matching for URLS

**Comment by mirestrepo** [comment]
oh.. yes and I guess I would need to register you as an user for you to test the changes. bummer. Thanks for looking at the code!

**Pull request merged**
