### PR TITLE
Feat preview channel

### PR DESCRIPTION
**Pull request by galenwinsor**
Includes not only Firebase preview deployment updates but also removing pro Fontawesome as a dependency.

### CODE REVIEW

**Comment by mirestrepo** [comment]
@galenwinsor  is the preview link working for you?

**Comment by galenwinsor** [comment]
> @galenwinsor is the preview link working for you?

Oh, no, I'm working on that now.

**Comment by mirestrepo** [comment]
It could be a build directory error? Here sis what my consul says
image

**Comment by galenwinsor** [comment]
> It could be a build directory error? Or a rewrite rule...Here sis what my console says
> image

It seems to be an issue with the Firebase dependency. Should be a pretty quick fix!

**Review by mirestrepo — CHANGES_REQUESTED** [review]
Could you remove from the README font awesome related instructions?

**Review by mirestrepo — APPROVED** [review]
I think it looks good. feel free to merge and see how it goes!

**Pull request merged**
